/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.fudan.androiddb.crawler.util;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class CrawlerServiceConstants {

  public static final int ERROR_CODE_CRAWLER_SERVICE_SUCCESS = 0;

  public static final int ERROR_CODE_CRAWLER_SERVICE_TASK_ALREADY_STARTED = -1;

  public static final int ERROR_CODE_CRAWLER_SERVICE_TASK_NOT_EXIST = -2;

  public static final int ERROR_CODE_CRAWLER_SERVICE_FAILED = -3;

}
